#!/usr/bin/env ruby
require "optparse"
require "xmlrpc/client"

commands = []
$post = {:description => '', :title => '', :categories =>[], :mt_keywords => ''}
$options = {:publish => true,
	    :xmlrpc => '/xmlrpc.php',
	    :blogid => 1,
	   }
$replace = []

def content(body)
  $post[:description] << body.to_s
end

def title(text)
  $post[:title] << text.to_s
end

def category(cat)
  $post[:categories] << cat.to_s.gsub("\n"," ")	# MetaWebLogAPI doesn't like newlines here
end

def tags(text)
  $post[:mt_keywords] << ',' if $post[:mt_keywords].size > 0
  $post[:mt_keywords] << text.to_s
end

def replace(what, with)
  $replace << [what, with]
end

def strip_single_newlines
  replace /([^\n])\n(?!\n)/m, '\1 '	# Replace lone EOLs with a space
end

def emit(name, content)
  endtag = "END_#{name.upcase}"
  puts "#{name} <<#{endtag}"
  puts content
  puts endtag
  puts ""
end

class Object
  def method_missing(symbol, *args)
    $options[symbol] = args.first
  end
end

optparse = OptionParser.new do |opts|
  opts.banner = 'usage: rump [-e "commands"] [-p FILE | -f ID | -u ID] [-v] file...'

  opts.on('-e', '--eval "commands"', 'Commands to override scripts') do |cmds|
    commands << cmds
  end

  opts.on('-f', '--fetch ID', 'Download post ID to rump source') do |id|
    $options[:fetch] = id
  end

  opts.on('-p', '--preview FILE', 'Preview using eruby template') do |templ|
    $preview_template = templ
  end

  opts.on('-u', '--update ID', 'Update post ID') do |id|
    $options[:update] = id
  end

  opts.on('-v', '--verbose', 'Verbose mode') do
    $options[:verbose] = true
  end
end

begin
  optparse.parse!
rescue OptionParser::InvalidOption, OptionParser::MissingArgument => e
  puts e
  puts optparse
  exit 1
end

ARGV.each do |file|
  if file == '-'
    eval STDIN.readlines.join
  else
    File.open file do |f|
      eval f.readlines.join
    end
  end
end

eval commands.join "\n" if commands.length > 0

if $replace.length > 0
  text = $post[:description]
  $replace.each { |what, with| text.gsub! what, with }
  $post[:description] = text
end

if $preview_template
  File.popen "eruby -Mf #{$preview_template}", "w" do |p|
    p.puts "$post = #{$post.inspect}"
    p.puts "$options = #{$options.inspect}"
  end
else
  raise "server not specified" unless $options[:server]
  raise "username not specified" unless $options[:username]
  raise "password not specified" unless $options[:password]
  server  = XMLRPC::Client.new($options[:server], $options[:xmlrpc])
  if $options[:fetch]
    $post = server.call("metaWeblog.getPost", $options[:fetch], $options[:username], $options[:password])
    puts "# Post ID #{$options[:fetch]} retrieved from #{$options[:server]} on #{Date.today} at #{Time.now}"
    puts ""
    emit "title", $post['title']
    $post['categories'].each { |cat| emit "category", cat }
    emit "tags", $post['mt_keywords']
    emit "content", $post['description']
  else
    if $options[:update]
      server.call("metaWeblog.editPost", $options[:update], $options[:username], $options[:password], $post, $options[:publish])
      result = $options[:update]	# post ID
    else
      result = server.call("metaWeblog.newPost", $options[:blogid], $options[:username], $options[:password], $post, $options[:publish])
    end
    if $options[:verbose]
      puts "Post ##{result} #{$options[:publish] ? 'published' : 'saved as draft'}"
      puts "Permalink: #{sprintf $options[:permalink], result}" if $options[:permalink]
    end
  end
end
